### ISSUE TITLE
support jupyterlab

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#40]
## Description

We can make it more comfortable to support birdy `native` client in JupyterLab:
- [x] support jupyter widget ... need currently a helper method
- [ ] provide list with possible input values ... can be used for widget
- [x] show available processes
- [x] display help

See example [notebook](https://github.com/cehbrecht/jupyterlab-notebooks/blob/master/copernicus-demo-july-2018/notebooks/wpsdemo.ipynb)

**Comment by tomLandry** [comment]
This is very relevant to PAVICS too, but I would have to check our development and scedule (which evolves quite rapidly).

**Comment by huard** [comment]
@cehbrecht Could you provide more info your vision ? 

At the moment, 
- `client.processes` returns the list of processes;
- `client.<process_identifier>? return the process documentation;

Are you thinking about a kind of process launch interface with widgets for each input ?

**Comment by cehbrecht** [comment]
@huard I think you have a better vision on what could be useful in a jupterlab environment :) Anything that makes usage more comfortable. Something to launch automatically a widget for user inputs and display the outputs (images only?). Inspiration comes from the Copernicus toolbox, here a screenshot:
https://github.com/cehbrecht/copernicus-talk-july-2018/blob/master/media/cds-toolbox-editor.png

... and a link to the toolbox:
https://cds.climate.copernicus.eu/cdsapp#!/home

**Comment by huard** [comment]
I don't think we want as a first step to stick as close as possible to emulate a native python function. There is some work that still needs to be done in the case where we send and receive the actual objects (not the references).  That to me would be the priority. The widgets are nice to have, but of secondary importance, to the exception maybe of the "cancel job" button. Ideally, this cancel button would be hooked to the jupyter controls, so that when we kill the backend, it also terminates the remote jobs.
