### ISSUE TITLE
default values for ComplexInput

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#60]
## Description

Running `emu.inout()` from the BirdyClient raises an error due to ( I think) the default value for ComplexInputs. I suppose the default should be set to None rather than an empty ComplexInput.

**Comment by cehbrecht** [comment]
@huard  ... this is due to the unclean design of `owslib.wps`:
https://github.com/geopython/OWSLib/blob/d0d66057784bc75caecc2f8cd0ced994ce116d33/owslib/wps.py#L1140

It misuses `defaultValue` for both literal and complex types. We should refactor this module on the way to WPS 2.0.0. 

For this current issue I have added PR #61 to handle `ComplexInput` in a special way.
